### ISSUE TITLE
This sample has not Data

### ISSUE THREAD

**Issue by HannahJSwystun** [vbtdung/playjava-template-rest#1]
Hello,

I run the sample project with SBT RUN and i found no DATA in the project!!
Could you tell me please how can i add Data in the Database to see what this project can do ?

Thank you in advance

**Comment by vbtdung** [comment]
Hello, I didn't find time to maintain and improve the original code. Basically the project has no persistent database, for non-persistent data, you can use the test_*.sh script files. For questions related to what the project can do, you can read through the REST API summary. Regards.

**Comment by HannahJSwystun** [comment]
Hi,

For instance, I am new on Play Framework and may be if there is some data or some samples it gonna to be very helpful for me...
Could you please make some initial data or a memory database just to see what the app could do .
